1. What is a Python library? Why do we use Python libraries?
Python Library: A Python library is a collection of modules and packages that contain pre-written code to perform common tasks. Examples include NumPy for numerical operations, Pandas for data analysis, and matplotlib for data visualization.
Why Use Python Libraries?: Using libraries helps speed up development by providing reusable code, reduces the chances of errors by relying on well-tested functions, and allows you to focus on the higher-level logic of your program rather than the implementation of basic functions.


What is the difference between Numpy array and List?
NumPy Array:
More efficient in terms of memory and performance.
Supports element-wise operations and broadcasting.
Homogeneous: all elements must be of the same data type.
List:
Can contain elements of different data types.
Less efficient for large-scale numerical computations.
Does not support element-wise operations or broadcasting.

In [1]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

shape = array.shape  # (3, 4) - 3 rows and 4 columns
size = array.size    # 12 - Total number of elements
dimension = array.ndim  # 2 - Number of dimensions

print(f"Shape: {shape}, Size: {size}, Dimension: {dimension}")


Shape: (3, 4), Size: 12, Dimension: 2


In [2]:
import numpy as np

array = np.array([[1, 2, 3, 4],
                  [5, 6, 7, 8],
                  [9, 10, 11, 12]])

first_row = array[0]
print(first_row)  # Output: [1 2 3 4]


[1 2 3 4]


In [3]:
element = array[2, 3]
print(element)  # Output: 12


12


In [4]:
odd_indexed_elements = array[:, 1::2]  # Extracts elements from columns with odd indices (1, 3)
print(odd_indexed_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [5]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.12800992 0.44766588 0.23856189]
 [0.93076881 0.73580271 0.93745189]
 [0.48929678 0.88319113 0.70756458]]


Describe the difference between np.random.rand and np.random.randn?
np.random.rand: Generates random numbers from a uniform distribution between 0 and 1.
np.random.randn: Generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

In [6]:
expanded_array = np.expand_dims(array, axis=0)
print(expanded_array)


[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]


In [7]:
transposed_array = array.T
print(transposed_array)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [8]:
# Element-wise multiplication
elementwise_multiplication = np.multiply(array, array)

# Matrix multiplication
matrix_multiplication = np.dot(array, array.T)  # Multiplying with its transpose for shape compatibility

# Addition
matrix_addition = np.add(array, array)

# Subtraction
matrix_subtraction = np.subtract(array, array)

# Division
matrix_division = np.divide(array, array)  # Dividing the array by itself

print("Element-wise Multiplication:\n", elementwise_multiplication)
print("Matrix Multiplication:\n", matrix_multiplication)
print("Addition:\n", matrix_addition)
print("Subtraction:\n", matrix_subtraction)
print("Division:\n", matrix_division)


Element-wise Multiplication:
 [[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix Multiplication:
 [[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]
Addition:
 [[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
Subtraction:
 [[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
Division:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Which function in Numpy can be used to swap the byte order of an array?
np.ndarray.byteswap(): This function swaps the byte order of the array elements.

What is the significance of the np.linalg.inv function?
np.linalg.inv: This function computes the inverse of a square matrix. It is used in linear algebra to find a matrix that, when multiplied with the original matrix, yields the identity matrix.

What does the np.reshape function do, and how is it used?
np.reshape: Changes the shape of an array without changing its data. It returns a new array with the specified shape.

In [9]:
reshaped_array = np.reshape(array, (2, 6))
print(reshaped_array)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


What is broadcasting in NumPy?
Broadcasting: It allows NumPy to perform element-wise operations on arrays of different shapes. Smaller arrays are "broadcast" to match the shape of larger arrays to perform operations without explicitly copying data.